URL_MARKDOWN: "https://raw.githubusercontent.com/jduijvenbode-WWF/ForestForesight/main/README.md"
AWS_BUCKET_NAME: "forestforesight-public"
AWS_BUCKET_REGION: "eu-west-1"
EARLIEST_DATA_DATE: "2021-01-01"
DEFAULT_GROUNDTRUTH: "groundtruth6m"
DATA_FOLDER: "" #Should be empty on develop only change it locally.
TEST:
  DATA_FOLDER: "tests/test_data"
  FF_PREP_QC_DATE: "2021-01-01"
  FF_PREP_COUNTRY: "BDI"
