name: R Project CI

on:
  pull_request:
    branches: [ develop ]

jobs:
  test-with-renv:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Set up R
      uses: r-lib/actions/setup-r@v2
      with:
        r-version: 'release'

    - name: Install system dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y \
          libcurl4-openssl-dev \
          libxml2-dev \
          libssl-dev \
          libudunits2-0 \
          libudunits2-dev \
          proj-bin \
          libproj-dev \
          libgdal-dev \
          libgeos-dev \
          libnetcdf-dev

    - name: Set up renv
      uses: r-lib/actions/setup-renv@v2

    - name: Install packages
      run: |
        Rscript -e 'devtools::install()'


    - name: Run unit tests
      run: |
        Rscript -e 'devtools::test()'
