name: Improving Code Readability
on:
  pull_request:
    branches: [ "develop" ]

jobs:
  styling-linting-the-code:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0  # Fetch all history to get the previous commit

    - name: Set up R library environment using custom actions
      uses: r-lib/actions/setup-r@v2

    - name: Install Lintr, Styler and Roxygen2
      run: |
        Rscript -e "install.packages(c('lintr', 'styler', 'roxygen2'), repos = 'https://cran.rstudio.com/')"

    - name: Style R code
      run: |
        Rscript -e "styler::style_pkg(include_roxygen_examples = FALSE); warnings()"

    - name: Check for changes by styler
      id: check_styler_changes
      run: |
        if git diff --quiet; then
          echo "No changes made by styler."
          echo "changes_made=false" >> $GITHUB_ENV
        else
          echo "Changes made by styler."
          echo "changes_made=true" >> $GITHUB_ENV
        fi
  
    - name: Fetch latest changes if styler made a change
      if: env.changes_made == 'true'
      run: |
        git fetch origin ${GITHUB_HEAD_REF}:${GITHUB_HEAD_REF}

    - name: Commit changes
      if: env.changes_made == 'true'
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        git config --global user.name 'github-actions[bot]'
        git config --global user.email 'github-actions[bot]@users.noreply.github.com'
        git add .
        git commit -m 'Style code with styler'
        git pull --rebase origin ${GITHUB_HEAD_REF}
        git push origin HEAD:refs/heads/${GITHUB_HEAD_REF}

    - name: Fetch the latest changes if there's a push from styler update
      if: env.changes_made == 'true' 
      run: |
        git fetch origin ${GITHUB_HEAD_REF}        
        COMMIT_HASH=$(git rev-parse origin/${GITHUB_HEAD_REF}^1)
        COMMIT_MESSAGE=$(git log -1 --pretty=%B $COMMIT_HASH)
        COMMIT_AUTHOR=$(git log -1 --pretty=format:'%an' $COMMIT_HASH)
        echo "updating the codebase with $COMMIT_MESSAGE from $COMMIT_AUTHOR"

    - name: Run lintr
      run: |
        Rscript -e "result <- lintr::lint_package(); count <- length(result); cat('Number of lintr comments generated:', count, '\n')"