name: R Tests
on:
  pull_request:
    branches: [ "develop" ]

jobs:
  Testing-package:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1

    - name: Install system dependencies
      run: |
        sudo apt-get update
        sudo apt-get install libcurl4-openssl-dev
        sudo apt-get install libharfbuzz-dev libfribidi-dev
        sudo apt-get install -y libudunits2-dev libgdal-dev libgeos-dev libproj-dev

    - name: Set up R library environment using custom actions
      uses: r-lib/actions/setup-r@v2

    - name: Install renv package
      run: |
        Rscript -e "install.packages('renv', repos = 'https://cran.rstudio.com/')"

    - name: Initialize renv and snapshot 
      run: |
        Rscript -e "renv::init(); renv::snapshot()"
        
    - name: Show installed R packages
      run: |
        Rscript -e "installed <- installed.packages(); print(installed[,c('Package', 'Version')])"

    - name: Run Tests
      run: |
        Rscript -e 'install.packages(c("devtools", "testthat"), repos = "https://cran.rstudio.com/")'
        Rscript -e 'devtools::load_all()'
        Rscript -e 'testthat::test_dir("tests/testthat")'